### ISSUE TITLE
Handle parameters

### ISSUE THREAD

**Issue by fjborquez** [TomerRon/cordless#23]
Hey, thanks for this package!, I saw it in Reddit a few days ago.
I'm trying to accept parameters in my bot, but i dunno understand how.

Can you gimme an example?

Greetings from Chile!

**Comment by TomerRon** [comment]
Hey,

You can use `msg.content` to access the body of the message, you can then do whatever string operations you want on this string to extract the parameters, depending on the behavior you want.

If you want to extract one parameter:

```ts
const myFn = {
  // ...
  condition: (msg) => msg.content.startsWith('!someCommand '),
  callback: (msg) => {
    const param = msg.content.split(' ')[1]
  }
}
```

If you want to extract many parameters:

```ts
const myFn = {
  // ...
  condition: (msg) => msg.content.startsWith('!someCommand '),
  callback: (msg) => {
    const [command, ...params] = msg.content.split(' ')
  }
}
```

If you want more advanced, CLI-like behavior (for example being able to pass flags (`-f`) or key-value pairs (`--foo=bar`)), it's probably best to use a package to handle that. Maybe [minimist](https://github.com/substack/minimist) or [commander.js](https://github.com/tj/commander.js) would work well for that.

Hope that helps!

**Comment by fjborquez** [comment]
thanks, I thought there was other form to do that and I was confused ahaha
